version: '3'

services:
  database:
    image: mysql:${MYSQL_VERSION:-8}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-tb_back}
      MYSQL_USER: ${MYSQL_USER:-default_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-default_password}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_password}
    restart: unless-stopped
    ports:
      - "3630:3306"
    volumes:
      - database_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1

volumes:
  database_data: